services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ThieleUndKlose\Autotranslate\:
    resource: '../Classes/*'

  ThieleUndKlose\Autotranslate\EventListener\GlossarySyncButtonBarListener:
    tags:
      - name: event.listener
        identifier: 'autotranslate/glossary-sync-button-bar'
        event: TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent

  ThieleUndKlose\Autotranslate\EventListener\GlossaryRecordListListener:
    tags:
      - name: event.listener
        identifier: 'autotranslate/glossary-sync-record-list'
        event: TYPO3\CMS\Backend\Controller\Event\RenderAdditionalContentToRecordListEvent

  ThieleUndKlose\Autotranslate\EventListener\GlossaryPageLayoutListener:
    tags:
      - name: event.listener
        identifier: 'autotranslate/glossary-sync-page-info'
        event: TYPO3\CMS\Backend\Controller\Event\ModifyPageLayoutContentEvent

  ThieleUndKlose\Autotranslate\Controller\BatchTranslationController:
    public: true

  ThieleUndKlose\Autotranslate\Service\GlossaryService:
    public: true

  ThieleUndKlose\Autotranslate\Service\DeeplTranslationClient:
    public: true

  ThieleUndKlose\Autotranslate\Service\DeeplTranslationClientInterface:
    alias: ThieleUndKlose\Autotranslate\Service\DeeplTranslationClient
    public: true

  ThieleUndKlose\Autotranslate\Service\GlossarySyncService:
    public: true

  ThieleUndKlose\Autotranslate\Controller\GlossarySyncController:
    public: true

  ThieleUndKlose\Autotranslate\Command\SyncGlossary:
    tags:
      - name: console.command
        command: "autotranslate:glossary:sync"
        description: "Synchronize Autotranslate glossary records with the DeepL API."
        schedulable: true

  ThieleUndKlose\Autotranslate\Command\BatchTranslation:
    tags:
      - name: console.command
        command: "autotranslate:batch:run"
        description: "Command for automatic translation of a number of elements."
        schedulable: false

  ThieleUndKlose\Autotranslate\Command\SetAutotranslateLanguages:
    tags:
      - name: console.command
        command: "autotranslate:set-languages"
        description: "Set autotranslate_languages field for existing records."
        schedulable: false

  ThieleUndKlose\Autotranslate\TsConfig\Loader:
    public: true
    tags:
      - name: event.listener
        identifier: 'add-page-configuration'
        event: TYPO3\CMS\Core\TypoScript\IncludeTree\Event\ModifyLoadedPageTsConfigEvent
        method: 'addPageConfiguration'

  ThieleUndKlose\Autotranslate\Service\BatchTranslationRunner:
    public: true

  ThieleUndKlose\Autotranslate\Hooks\DataHandler:
    public: true

